// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/snverb/v1alpha1/snverb.proto

package snverb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1alpha1 "gosuda.org/supernet/proto/maddr/v1alpha1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Algorithm int32

const (
	Algorithm_ED25519   Algorithm = 0
	Algorithm_ED448     Algorithm = 1
	Algorithm_MLDSA44   Algorithm = 2
	Algorithm_MLDSA65   Algorithm = 3
	Algorithm_MLDSA87   Algorithm = 4
	Algorithm_X25519    Algorithm = 5
	Algorithm_X448      Algorithm = 6
	Algorithm_MLKEM512  Algorithm = 7
	Algorithm_MLKEM768  Algorithm = 8
	Algorithm_MLKEM1024 Algorithm = 9
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ED25519",
		1: "ED448",
		2: "MLDSA44",
		3: "MLDSA65",
		4: "MLDSA87",
		5: "X25519",
		6: "X448",
		7: "MLKEM512",
		8: "MLKEM768",
		9: "MLKEM1024",
	}
	Algorithm_value = map[string]int32{
		"ED25519":   0,
		"ED448":     1,
		"MLDSA44":   2,
		"MLDSA65":   3,
		"MLDSA87":   4,
		"X25519":    5,
		"X448":      6,
		"MLKEM512":  7,
		"MLKEM768":  8,
		"MLKEM1024": 9,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_snverb_v1alpha1_snverb_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_proto_snverb_v1alpha1_snverb_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_proto_snverb_v1alpha1_snverb_proto_rawDescGZIP(), []int{0}
}

type MultiSignaturePolicy int32

const (
	MultiSignaturePolicy_REQUIRE_ALL    MultiSignaturePolicy = 0 // All signatures are required
	MultiSignaturePolicy_REQUIRE_ANY    MultiSignaturePolicy = 1 // Any signature is sufficient
	MultiSignaturePolicy_REQUIRE_QUORUM MultiSignaturePolicy = 2 // A quorum of signatures is required
)

// Enum value maps for MultiSignaturePolicy.
var (
	MultiSignaturePolicy_name = map[int32]string{
		0: "REQUIRE_ALL",
		1: "REQUIRE_ANY",
		2: "REQUIRE_QUORUM",
	}
	MultiSignaturePolicy_value = map[string]int32{
		"REQUIRE_ALL":    0,
		"REQUIRE_ANY":    1,
		"REQUIRE_QUORUM": 2,
	}
)

func (x MultiSignaturePolicy) Enum() *MultiSignaturePolicy {
	p := new(MultiSignaturePolicy)
	*p = x
	return p
}

func (x MultiSignaturePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MultiSignaturePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_snverb_v1alpha1_snverb_proto_enumTypes[1].Descriptor()
}

func (MultiSignaturePolicy) Type() protoreflect.EnumType {
	return &file_proto_snverb_v1alpha1_snverb_proto_enumTypes[1]
}

func (x MultiSignaturePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MultiSignaturePolicy.Descriptor instead.
func (MultiSignaturePolicy) EnumDescriptor() ([]byte, []int) {
	return file_proto_snverb_v1alpha1_snverb_proto_rawDescGZIP(), []int{1}
}

type SignaturePolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalSigners    int64                  `protobuf:"varint,1,opt,name=total_signers,json=totalSigners,proto3" json:"total_signers,omitempty"`                                        // Total number of available signers
	TotalSignatures int64                  `protobuf:"varint,2,opt,name=total_signatures,json=totalSignatures,proto3" json:"total_signatures,omitempty"`                               // Total number of signatures
	Threshold       int64                  `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`                                                                  // Minimum number of vaild signatures required
	MultiSignature  MultiSignaturePolicy   `protobuf:"varint,4,opt,name=multi_signature,json=multiSignature,proto3,enum=snverb.MultiSignaturePolicy" json:"multi_signature,omitempty"` // Type of multi-signature policy
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignaturePolicy) Reset() {
	*x = SignaturePolicy{}
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignaturePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignaturePolicy) ProtoMessage() {}

func (x *SignaturePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignaturePolicy.ProtoReflect.Descriptor instead.
func (*SignaturePolicy) Descriptor() ([]byte, []int) {
	return file_proto_snverb_v1alpha1_snverb_proto_rawDescGZIP(), []int{0}
}

func (x *SignaturePolicy) GetTotalSigners() int64 {
	if x != nil {
		return x.TotalSigners
	}
	return 0
}

func (x *SignaturePolicy) GetTotalSignatures() int64 {
	if x != nil {
		return x.TotalSignatures
	}
	return 0
}

func (x *SignaturePolicy) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *SignaturePolicy) GetMultiSignature() MultiSignaturePolicy {
	if x != nil {
		return x.MultiSignature
	}
	return MultiSignaturePolicy_REQUIRE_ALL
}

type SignaturePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in seconds
	Nonce         int64                  `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`         // Unique nonce for the signature
	Policy        *SignaturePolicy       `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`        // Signature policy
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`            // Data to be signed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignaturePayload) Reset() {
	*x = SignaturePayload{}
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignaturePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignaturePayload) ProtoMessage() {}

func (x *SignaturePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignaturePayload.ProtoReflect.Descriptor instead.
func (*SignaturePayload) Descriptor() ([]byte, []int) {
	return file_proto_snverb_v1alpha1_snverb_proto_rawDescGZIP(), []int{1}
}

func (x *SignaturePayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SignaturePayload) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *SignaturePayload) GetPolicy() *SignaturePolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *SignaturePayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     Algorithm              `protobuf:"varint,1,opt,name=algorithm,proto3,enum=snverb.Algorithm" json:"algorithm,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_proto_snverb_v1alpha1_snverb_proto_rawDescGZIP(), []int{2}
}

func (x *PublicKey) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ED25519
}

func (x *PublicKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     Algorithm              `protobuf:"varint,1,opt,name=algorithm,proto3,enum=snverb.Algorithm" json:"algorithm,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_proto_snverb_v1alpha1_snverb_proto_rawDescGZIP(), []int{3}
}

func (x *Signature) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ED25519
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKeys    []*PublicKey           `protobuf:"bytes,1,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"` // List of public keys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_proto_snverb_v1alpha1_snverb_proto_rawDescGZIP(), []int{4}
}

func (x *Identity) GetPublicKeys() []*PublicKey {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type NodeMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *v1alpha1.AddressSet   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`   // Node address
	Identity      *Identity              `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"` // Node identity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetadata) Reset() {
	*x = NodeMetadata{}
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetadata) ProtoMessage() {}

func (x *NodeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snverb_v1alpha1_snverb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetadata.ProtoReflect.Descriptor instead.
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return file_proto_snverb_v1alpha1_snverb_proto_rawDescGZIP(), []int{5}
}

func (x *NodeMetadata) GetAddress() *v1alpha1.AddressSet {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *NodeMetadata) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

var File_proto_snverb_v1alpha1_snverb_proto protoreflect.FileDescriptor

const file_proto_snverb_v1alpha1_snverb_proto_rawDesc = "" +
	"\n" +
	"\"proto/snverb/v1alpha1/snverb.proto\x12\x06snverb\x1a proto/maddr/v1alpha1/maddr.proto\"\xc6\x01\n" +
	"\x0fSignaturePolicy\x12#\n" +
	"\rtotal_signers\x18\x01 \x01(\x03R\ftotalSigners\x12)\n" +
	"\x10total_signatures\x18\x02 \x01(\x03R\x0ftotalSignatures\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x03R\tthreshold\x12E\n" +
	"\x0fmulti_signature\x18\x04 \x01(\x0e2\x1c.snverb.MultiSignaturePolicyR\x0emultiSignature\"\x8b\x01\n" +
	"\x10SignaturePayload\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x03R\x05nonce\x12/\n" +
	"\x06policy\x18\x03 \x01(\v2\x17.snverb.SignaturePolicyR\x06policy\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"N\n" +
	"\tPublicKey\x12/\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x11.snverb.AlgorithmR\talgorithm\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"Z\n" +
	"\tSignature\x12/\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x11.snverb.AlgorithmR\talgorithm\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\">\n" +
	"\bIdentity\x122\n" +
	"\vpublic_keys\x18\x01 \x03(\v2\x11.snverb.PublicKeyR\n" +
	"publicKeys\"i\n" +
	"\fNodeMetadata\x12+\n" +
	"\aaddress\x18\x01 \x01(\v2\x11.maddr.AddressSetR\aaddress\x12,\n" +
	"\bidentity\x18\x02 \x01(\v2\x10.snverb.IdentityR\bidentity*\x8b\x01\n" +
	"\tAlgorithm\x12\v\n" +
	"\aED25519\x10\x00\x12\t\n" +
	"\x05ED448\x10\x01\x12\v\n" +
	"\aMLDSA44\x10\x02\x12\v\n" +
	"\aMLDSA65\x10\x03\x12\v\n" +
	"\aMLDSA87\x10\x04\x12\n" +
	"\n" +
	"\x06X25519\x10\x05\x12\b\n" +
	"\x04X448\x10\x06\x12\f\n" +
	"\bMLKEM512\x10\a\x12\f\n" +
	"\bMLKEM768\x10\b\x12\r\n" +
	"\tMLKEM1024\x10\t*L\n" +
	"\x14MultiSignaturePolicy\x12\x0f\n" +
	"\vREQUIRE_ALL\x10\x00\x12\x0f\n" +
	"\vREQUIRE_ANY\x10\x01\x12\x12\n" +
	"\x0eREQUIRE_QUORUM\x10\x02B\x83\x01\n" +
	"\n" +
	"com.snverbB\vSnverbProtoP\x01Z0gosuda.org/supernet/proto/snverb/v1alpha1;snverb\xa2\x02\x03SXX\xaa\x02\x06Snverb\xca\x02\x06Snverb\xe2\x02\x12Snverb\\GPBMetadata\xea\x02\x06Snverbb\x06proto3"

var (
	file_proto_snverb_v1alpha1_snverb_proto_rawDescOnce sync.Once
	file_proto_snverb_v1alpha1_snverb_proto_rawDescData []byte
)

func file_proto_snverb_v1alpha1_snverb_proto_rawDescGZIP() []byte {
	file_proto_snverb_v1alpha1_snverb_proto_rawDescOnce.Do(func() {
		file_proto_snverb_v1alpha1_snverb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_snverb_v1alpha1_snverb_proto_rawDesc), len(file_proto_snverb_v1alpha1_snverb_proto_rawDesc)))
	})
	return file_proto_snverb_v1alpha1_snverb_proto_rawDescData
}

var file_proto_snverb_v1alpha1_snverb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_snverb_v1alpha1_snverb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_snverb_v1alpha1_snverb_proto_goTypes = []any{
	(Algorithm)(0),              // 0: snverb.Algorithm
	(MultiSignaturePolicy)(0),   // 1: snverb.MultiSignaturePolicy
	(*SignaturePolicy)(nil),     // 2: snverb.SignaturePolicy
	(*SignaturePayload)(nil),    // 3: snverb.SignaturePayload
	(*PublicKey)(nil),           // 4: snverb.PublicKey
	(*Signature)(nil),           // 5: snverb.Signature
	(*Identity)(nil),            // 6: snverb.Identity
	(*NodeMetadata)(nil),        // 7: snverb.NodeMetadata
	(*v1alpha1.AddressSet)(nil), // 8: maddr.AddressSet
}
var file_proto_snverb_v1alpha1_snverb_proto_depIdxs = []int32{
	1, // 0: snverb.SignaturePolicy.multi_signature:type_name -> snverb.MultiSignaturePolicy
	2, // 1: snverb.SignaturePayload.policy:type_name -> snverb.SignaturePolicy
	0, // 2: snverb.PublicKey.algorithm:type_name -> snverb.Algorithm
	0, // 3: snverb.Signature.algorithm:type_name -> snverb.Algorithm
	4, // 4: snverb.Identity.public_keys:type_name -> snverb.PublicKey
	8, // 5: snverb.NodeMetadata.address:type_name -> maddr.AddressSet
	6, // 6: snverb.NodeMetadata.identity:type_name -> snverb.Identity
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_snverb_v1alpha1_snverb_proto_init() }
func file_proto_snverb_v1alpha1_snverb_proto_init() {
	if File_proto_snverb_v1alpha1_snverb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_snverb_v1alpha1_snverb_proto_rawDesc), len(file_proto_snverb_v1alpha1_snverb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_snverb_v1alpha1_snverb_proto_goTypes,
		DependencyIndexes: file_proto_snverb_v1alpha1_snverb_proto_depIdxs,
		EnumInfos:         file_proto_snverb_v1alpha1_snverb_proto_enumTypes,
		MessageInfos:      file_proto_snverb_v1alpha1_snverb_proto_msgTypes,
	}.Build()
	File_proto_snverb_v1alpha1_snverb_proto = out.File
	file_proto_snverb_v1alpha1_snverb_proto_goTypes = nil
	file_proto_snverb_v1alpha1_snverb_proto_depIdxs = nil
}
