// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/maddr/v1alpha1/maddr.proto

package maddr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED  Protocol = 0
	Protocol_PROTOCOL_IP4          Protocol = 1  // IPv4 address, e.g., "1.1.1.1"
	Protocol_PROTOCOL_IP6          Protocol = 2  // IPv6 address, e.g., "2606:4700:4700::1111"
	Protocol_PROTOCOL_DNS4         Protocol = 3  // DNS address, e.g., "example.com"
	Protocol_PROTOCOL_DNS6         Protocol = 4  // DNS address with IPv6, e.g., "example.com"
	Protocol_PROTOCOL_TCP          Protocol = 5  // TCP protocol and port, e.g., "7496"
	Protocol_PROTOCOL_UDP          Protocol = 6  // UDP protocol and port, e.g., "7496"
	Protocol_PROTOCOL_QUIC         Protocol = 7  // QUIC protocol and port, e.g., "7496" with optional associated Certificate Fingerprint
	Protocol_PROTOCOL_HTTP         Protocol = 8  // HTTP protocol, with streaming support
	Protocol_PROTOCOL_GRPC         Protocol = 9  // gRPC protocol, with streaming support
	Protocol_PROTOCOL_WEBRTC       Protocol = 10 // WebRTC Data Channel Transport
	Protocol_PROTOCOL_WEBSOCKET    Protocol = 11 // WebSocket protocol, with streaming support
	Protocol_PROTOCOL_WEBTRANSPORT Protocol = 12 // WebTransport protocol, with streaming support
	Protocol_PROTOCOL_BLE          Protocol = 20 // Bluetooth Low Energy protocol WIP
	Protocol_PROTOCOL_UWB          Protocol = 21 // Ultra-Wideband protocol WIP
	Protocol_PROTOCOL_LORA         Protocol = 22 // LoRA protocol WIP
	Protocol_PROTOCOL_ZWAVE        Protocol = 23 // Z-Wave protocol WIP
	Protocol_PROTOCOL_ZIGBEE       Protocol = 24 // Zigbee protocol WIP
	Protocol_PROTOCOL_SNRELAY      Protocol = 30 // SuperNet Relay Protocol
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0:  "PROTOCOL_UNSPECIFIED",
		1:  "PROTOCOL_IP4",
		2:  "PROTOCOL_IP6",
		3:  "PROTOCOL_DNS4",
		4:  "PROTOCOL_DNS6",
		5:  "PROTOCOL_TCP",
		6:  "PROTOCOL_UDP",
		7:  "PROTOCOL_QUIC",
		8:  "PROTOCOL_HTTP",
		9:  "PROTOCOL_GRPC",
		10: "PROTOCOL_WEBRTC",
		11: "PROTOCOL_WEBSOCKET",
		12: "PROTOCOL_WEBTRANSPORT",
		20: "PROTOCOL_BLE",
		21: "PROTOCOL_UWB",
		22: "PROTOCOL_LORA",
		23: "PROTOCOL_ZWAVE",
		24: "PROTOCOL_ZIGBEE",
		30: "PROTOCOL_SNRELAY",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED":  0,
		"PROTOCOL_IP4":          1,
		"PROTOCOL_IP6":          2,
		"PROTOCOL_DNS4":         3,
		"PROTOCOL_DNS6":         4,
		"PROTOCOL_TCP":          5,
		"PROTOCOL_UDP":          6,
		"PROTOCOL_QUIC":         7,
		"PROTOCOL_HTTP":         8,
		"PROTOCOL_GRPC":         9,
		"PROTOCOL_WEBRTC":       10,
		"PROTOCOL_WEBSOCKET":    11,
		"PROTOCOL_WEBTRANSPORT": 12,
		"PROTOCOL_BLE":          20,
		"PROTOCOL_UWB":          21,
		"PROTOCOL_LORA":         22,
		"PROTOCOL_ZWAVE":        23,
		"PROTOCOL_ZIGBEE":       24,
		"PROTOCOL_SNRELAY":      30,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_maddr_v1alpha1_maddr_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_proto_maddr_v1alpha1_maddr_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_maddr_v1alpha1_maddr_proto_rawDescGZIP(), []int{0}
}

type Address struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Protocol       Protocol               `protobuf:"varint,1,opt,name=protocol,proto3,enum=maddr.Protocol" json:"protocol,omitempty"` // Protocol type of the address
	Address        []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                        // address data
	Local          *Address               `protobuf:"bytes,3,opt,name=local,proto3,oneof" json:"local,omitempty"`
	Identifier     []byte                 `protobuf:"bytes,4,opt,name=identifier,proto3,oneof" json:"identifier,omitempty"`                               // Unique identifier for the address
	AssociatedData []byte                 `protobuf:"bytes,5,opt,name=associated_data,json=associatedData,proto3,oneof" json:"associated_data,omitempty"` // Additional data associated with the address
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_maddr_v1alpha1_maddr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maddr_v1alpha1_maddr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_maddr_v1alpha1_maddr_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *Address) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Address) GetLocal() *Address {
	if x != nil {
		return x.Local
	}
	return nil
}

func (x *Address) GetIdentifier() []byte {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Address) GetAssociatedData() []byte {
	if x != nil {
		return x.AssociatedData
	}
	return nil
}

type AddressList struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Addresses       []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ClientProtocols []Protocol             `protobuf:"varint,2,rep,packed,name=client_protocols,json=clientProtocols,proto3,enum=maddr.Protocol" json:"client_protocols,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddressList) Reset() {
	*x = AddressList{}
	mi := &file_proto_maddr_v1alpha1_maddr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressList) ProtoMessage() {}

func (x *AddressList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maddr_v1alpha1_maddr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressList.ProtoReflect.Descriptor instead.
func (*AddressList) Descriptor() ([]byte, []int) {
	return file_proto_maddr_v1alpha1_maddr_proto_rawDescGZIP(), []int{1}
}

func (x *AddressList) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *AddressList) GetClientProtocols() []Protocol {
	if x != nil {
		return x.ClientProtocols
	}
	return nil
}

var File_proto_maddr_v1alpha1_maddr_proto protoreflect.FileDescriptor

const file_proto_maddr_v1alpha1_maddr_proto_rawDesc = "" +
	"\n" +
	" proto/maddr/v1alpha1/maddr.proto\x12\x05maddr\"\xfb\x01\n" +
	"\aAddress\x12+\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x0f.maddr.ProtocolR\bprotocol\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12)\n" +
	"\x05local\x18\x03 \x01(\v2\x0e.maddr.AddressH\x00R\x05local\x88\x01\x01\x12#\n" +
	"\n" +
	"identifier\x18\x04 \x01(\fH\x01R\n" +
	"identifier\x88\x01\x01\x12,\n" +
	"\x0fassociated_data\x18\x05 \x01(\fH\x02R\x0eassociatedData\x88\x01\x01B\b\n" +
	"\x06_localB\r\n" +
	"\v_identifierB\x12\n" +
	"\x10_associated_data\"w\n" +
	"\vAddressList\x12,\n" +
	"\taddresses\x18\x01 \x03(\v2\x0e.maddr.AddressR\taddresses\x12:\n" +
	"\x10client_protocols\x18\x02 \x03(\x0e2\x0f.maddr.ProtocolR\x0fclientProtocols*\x89\x03\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_IP4\x10\x01\x12\x10\n" +
	"\fPROTOCOL_IP6\x10\x02\x12\x11\n" +
	"\rPROTOCOL_DNS4\x10\x03\x12\x11\n" +
	"\rPROTOCOL_DNS6\x10\x04\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x05\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x06\x12\x11\n" +
	"\rPROTOCOL_QUIC\x10\a\x12\x11\n" +
	"\rPROTOCOL_HTTP\x10\b\x12\x11\n" +
	"\rPROTOCOL_GRPC\x10\t\x12\x13\n" +
	"\x0fPROTOCOL_WEBRTC\x10\n" +
	"\x12\x16\n" +
	"\x12PROTOCOL_WEBSOCKET\x10\v\x12\x19\n" +
	"\x15PROTOCOL_WEBTRANSPORT\x10\f\x12\x10\n" +
	"\fPROTOCOL_BLE\x10\x14\x12\x10\n" +
	"\fPROTOCOL_UWB\x10\x15\x12\x11\n" +
	"\rPROTOCOL_LORA\x10\x16\x12\x12\n" +
	"\x0ePROTOCOL_ZWAVE\x10\x17\x12\x13\n" +
	"\x0fPROTOCOL_ZIGBEE\x10\x18\x12\x14\n" +
	"\x10PROTOCOL_SNRELAY\x10\x1eB{\n" +
	"\tcom.maddrB\n" +
	"MaddrProtoP\x01Z.gosuda.org/supernet/proto/maddr/v1alpha1;maddr\xa2\x02\x03MXX\xaa\x02\x05Maddr\xca\x02\x05Maddr\xe2\x02\x11Maddr\\GPBMetadata\xea\x02\x05Maddrb\x06proto3"

var (
	file_proto_maddr_v1alpha1_maddr_proto_rawDescOnce sync.Once
	file_proto_maddr_v1alpha1_maddr_proto_rawDescData []byte
)

func file_proto_maddr_v1alpha1_maddr_proto_rawDescGZIP() []byte {
	file_proto_maddr_v1alpha1_maddr_proto_rawDescOnce.Do(func() {
		file_proto_maddr_v1alpha1_maddr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_maddr_v1alpha1_maddr_proto_rawDesc), len(file_proto_maddr_v1alpha1_maddr_proto_rawDesc)))
	})
	return file_proto_maddr_v1alpha1_maddr_proto_rawDescData
}

var file_proto_maddr_v1alpha1_maddr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_maddr_v1alpha1_maddr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_maddr_v1alpha1_maddr_proto_goTypes = []any{
	(Protocol)(0),       // 0: maddr.Protocol
	(*Address)(nil),     // 1: maddr.Address
	(*AddressList)(nil), // 2: maddr.AddressList
}
var file_proto_maddr_v1alpha1_maddr_proto_depIdxs = []int32{
	0, // 0: maddr.Address.protocol:type_name -> maddr.Protocol
	1, // 1: maddr.Address.local:type_name -> maddr.Address
	1, // 2: maddr.AddressList.addresses:type_name -> maddr.Address
	0, // 3: maddr.AddressList.client_protocols:type_name -> maddr.Protocol
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_maddr_v1alpha1_maddr_proto_init() }
func file_proto_maddr_v1alpha1_maddr_proto_init() {
	if File_proto_maddr_v1alpha1_maddr_proto != nil {
		return
	}
	file_proto_maddr_v1alpha1_maddr_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_maddr_v1alpha1_maddr_proto_rawDesc), len(file_proto_maddr_v1alpha1_maddr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_maddr_v1alpha1_maddr_proto_goTypes,
		DependencyIndexes: file_proto_maddr_v1alpha1_maddr_proto_depIdxs,
		EnumInfos:         file_proto_maddr_v1alpha1_maddr_proto_enumTypes,
		MessageInfos:      file_proto_maddr_v1alpha1_maddr_proto_msgTypes,
	}.Build()
	File_proto_maddr_v1alpha1_maddr_proto = out.File
	file_proto_maddr_v1alpha1_maddr_proto_goTypes = nil
	file_proto_maddr_v1alpha1_maddr_proto_depIdxs = nil
}
