// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/maddr/v1alpha1/maddr.proto

package maddr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED   Protocol = 0
	Protocol_PROTOCOL_IP4           Protocol = 1
	Protocol_PROTOCOL_IP6           Protocol = 2
	Protocol_PROTOCOL_TCP           Protocol = 3
	Protocol_PROTOCOL_UDP           Protocol = 4
	Protocol_PROTOCOL_WEBRTC_SIGNAL Protocol = 5
	Protocol_PROTOCOL_HTTP          Protocol = 6
	Protocol_PROTOCOL_HTTPS         Protocol = 7
	Protocol_PROTOCOL_WS            Protocol = 8
	Protocol_PROTOCOL_WSS           Protocol = 9
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_IP4",
		2: "PROTOCOL_IP6",
		3: "PROTOCOL_TCP",
		4: "PROTOCOL_UDP",
		5: "PROTOCOL_WEBRTC_SIGNAL",
		6: "PROTOCOL_HTTP",
		7: "PROTOCOL_HTTPS",
		8: "PROTOCOL_WS",
		9: "PROTOCOL_WSS",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED":   0,
		"PROTOCOL_IP4":           1,
		"PROTOCOL_IP6":           2,
		"PROTOCOL_TCP":           3,
		"PROTOCOL_UDP":           4,
		"PROTOCOL_WEBRTC_SIGNAL": 5,
		"PROTOCOL_HTTP":          6,
		"PROTOCOL_HTTPS":         7,
		"PROTOCOL_WS":            8,
		"PROTOCOL_WSS":           9,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_maddr_v1alpha1_maddr_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_proto_maddr_v1alpha1_maddr_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_maddr_v1alpha1_maddr_proto_rawDescGZIP(), []int{0}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     uint64                 `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=maddr.Protocol" json:"protocol,omitempty"`
	RelayAddress  *Address               `protobuf:"bytes,3,opt,name=relay_address,json=relayAddress,proto3,oneof" json:"relay_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_maddr_v1alpha1_maddr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maddr_v1alpha1_maddr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_maddr_v1alpha1_maddr_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Address) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *Address) GetRelayAddress() *Address {
	if x != nil {
		return x.RelayAddress
	}
	return nil
}

type AddressSet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Addresses       []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ClientProtocols []Protocol             `protobuf:"varint,2,rep,packed,name=client_protocols,json=clientProtocols,proto3,enum=maddr.Protocol" json:"client_protocols,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddressSet) Reset() {
	*x = AddressSet{}
	mi := &file_proto_maddr_v1alpha1_maddr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressSet) ProtoMessage() {}

func (x *AddressSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maddr_v1alpha1_maddr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressSet.ProtoReflect.Descriptor instead.
func (*AddressSet) Descriptor() ([]byte, []int) {
	return file_proto_maddr_v1alpha1_maddr_proto_rawDescGZIP(), []int{1}
}

func (x *AddressSet) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *AddressSet) GetClientProtocols() []Protocol {
	if x != nil {
		return x.ClientProtocols
	}
	return nil
}

var File_proto_maddr_v1alpha1_maddr_proto protoreflect.FileDescriptor

const file_proto_maddr_v1alpha1_maddr_proto_rawDesc = "" +
	"\n" +
	" proto/maddr/v1alpha1/maddr.proto\x12\x05maddr\"\xa1\x01\n" +
	"\aAddress\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\x04R\tnetworkId\x12+\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x0f.maddr.ProtocolR\bprotocol\x128\n" +
	"\rrelay_address\x18\x03 \x01(\v2\x0e.maddr.AddressH\x00R\frelayAddress\x88\x01\x01B\x10\n" +
	"\x0e_relay_address\"v\n" +
	"\n" +
	"AddressSet\x12,\n" +
	"\taddresses\x18\x01 \x03(\v2\x0e.maddr.AddressR\taddresses\x12:\n" +
	"\x10client_protocols\x18\x02 \x03(\x0e2\x0f.maddr.ProtocolR\x0fclientProtocols*\xd2\x01\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_IP4\x10\x01\x12\x10\n" +
	"\fPROTOCOL_IP6\x10\x02\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x03\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x04\x12\x1a\n" +
	"\x16PROTOCOL_WEBRTC_SIGNAL\x10\x05\x12\x11\n" +
	"\rPROTOCOL_HTTP\x10\x06\x12\x12\n" +
	"\x0ePROTOCOL_HTTPS\x10\a\x12\x0f\n" +
	"\vPROTOCOL_WS\x10\b\x12\x10\n" +
	"\fPROTOCOL_WSS\x10\tB{\n" +
	"\tcom.maddrB\n" +
	"MaddrProtoP\x01Z.gosuda.org/supernet/proto/maddr/v1alpha1;maddr\xa2\x02\x03MXX\xaa\x02\x05Maddr\xca\x02\x05Maddr\xe2\x02\x11Maddr\\GPBMetadata\xea\x02\x05Maddrb\x06proto3"

var (
	file_proto_maddr_v1alpha1_maddr_proto_rawDescOnce sync.Once
	file_proto_maddr_v1alpha1_maddr_proto_rawDescData []byte
)

func file_proto_maddr_v1alpha1_maddr_proto_rawDescGZIP() []byte {
	file_proto_maddr_v1alpha1_maddr_proto_rawDescOnce.Do(func() {
		file_proto_maddr_v1alpha1_maddr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_maddr_v1alpha1_maddr_proto_rawDesc), len(file_proto_maddr_v1alpha1_maddr_proto_rawDesc)))
	})
	return file_proto_maddr_v1alpha1_maddr_proto_rawDescData
}

var file_proto_maddr_v1alpha1_maddr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_maddr_v1alpha1_maddr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_maddr_v1alpha1_maddr_proto_goTypes = []any{
	(Protocol)(0),      // 0: maddr.Protocol
	(*Address)(nil),    // 1: maddr.Address
	(*AddressSet)(nil), // 2: maddr.AddressSet
}
var file_proto_maddr_v1alpha1_maddr_proto_depIdxs = []int32{
	0, // 0: maddr.Address.protocol:type_name -> maddr.Protocol
	1, // 1: maddr.Address.relay_address:type_name -> maddr.Address
	1, // 2: maddr.AddressSet.addresses:type_name -> maddr.Address
	0, // 3: maddr.AddressSet.client_protocols:type_name -> maddr.Protocol
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_maddr_v1alpha1_maddr_proto_init() }
func file_proto_maddr_v1alpha1_maddr_proto_init() {
	if File_proto_maddr_v1alpha1_maddr_proto != nil {
		return
	}
	file_proto_maddr_v1alpha1_maddr_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_maddr_v1alpha1_maddr_proto_rawDesc), len(file_proto_maddr_v1alpha1_maddr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_maddr_v1alpha1_maddr_proto_goTypes,
		DependencyIndexes: file_proto_maddr_v1alpha1_maddr_proto_depIdxs,
		EnumInfos:         file_proto_maddr_v1alpha1_maddr_proto_enumTypes,
		MessageInfos:      file_proto_maddr_v1alpha1_maddr_proto_msgTypes,
	}.Build()
	File_proto_maddr_v1alpha1_maddr_proto = out.File
	file_proto_maddr_v1alpha1_maddr_proto_goTypes = nil
	file_proto_maddr_v1alpha1_maddr_proto_depIdxs = nil
}
